package com.arch.holy.model.bible;

import com.arch.holy.model.enums.SUPPLEMENT_TYPE;
import com.arch.holy.model.enums.TOME_ID;
import org.apache.commons.collections.BidiMap;
import org.apache.commons.collections.bidimap.DualHashBidiMap;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static com.arch.holy.model.enums.TOME_ID.*;

public class BibleConstants {

    // BIBLE METADATA CONSTANTS
    public static final int TOME_CARD_NUM_RANGE_START = 1;
    public static final int TOME_CARD_NUM_RANGE_END = 73;
    public static final int OLD_T_TOME_CARD_NUM_RANGE_START = 1;
    public static final int OLD_T_TOME_CARD_NUM_RANGE_END = 46;
    public static final int NEW_T_TOME_CARD_NUM_RANGE_START = 47;
    public static final int NEW_T_TOME_CARD_NUM_RANGE_END = 73;
    public static final int OLD_T_VERSE_CARD_NUM_RANGE_START = 1;
    public static final int OLD_T_VERSE_CARD_NUM_RANGE_END = 27626;
    public static final int NEW_T_VERSE_CARD_NUM_RANGE_START = 27627;
    public static final int NEW_T_VERSE_CARD_NUM_RANGE_END = 35567;
    public static final String RDZ_SIGLUM = "Rdz";
    public static final String WJ_SIGLUM = "Wj";
    public static final String KPL_SIGLUM = "Kpł";
    public static final String LB_SIGLUM = "Lb";
    public static final String PWT_SIGLUM = "Pwt";
    public static final String JOZ_SIGLUM = "Joz";
    public static final String SDZ_SIGLUM = "Sdz";
    public static final String RT_SIGLUM = "Rt";
    public static final String SM_1_SIGLUM = "1Sm";
    public static final String SM_2_SIGLUM = "2Sm";
    public static final String KRL_1_SIGLUM = "1Krl";
    public static final String KRL_2_SIGLUM = "2Krl";
    public static final String KRN_1_SIGLUM = "1Krn";
    public static final String KRN_2_SIGLUM = "2Krn";
    public static final String EZD_SIGLUM = "Ezd";
    public static final String NE_SIGLUM = "Ne";
    public static final String TB_SIGLUM = "Tb";
    public static final String JDT_SIGLUM = "Jdt";
    public static final String EST_SIGLUM = "Est";
    public static final String MCH_1_SIGLUM = "1Mch";
    public static final String MCH_2_SIGLUM = "2Mch";
    public static final String HI_SIGLUM = "Hi";
    public static final String PS_SIGLUM = "Ps";
    public static final String PRZ_SIGLUM = "Prz";
    public static final String KOH_SIGLUM = "Koh";
    public static final String PNP_SIGLUM = "Pnp";
    public static final String MDR_SIGLUM = "Mdr";
    public static final String SYR_SIGLUM = "Syr";
    public static final String IZ_SIGLUM = "Iz";
    public static final String JR_SIGLUM = "Jr";
    public static final String LM_SIGLUM = "Lm";
    public static final String BA_SIGLUM = "Ba";
    public static final String EZ_SIGLUM = "Ez";
    public static final String DN_SIGLUM = "Dn";
    public static final String OZ_SIGLUM = "Oz";
    public static final String JL_SIGLUM = "Jl";
    public static final String AM_SIGLUM = "Am";
    public static final String AB_SIGLUM = "Ab";
    public static final String JON_SIGLUM = "Jon";
    public static final String MI_SIGLUM = "Mi";
    public static final String NA_SIGLUM = "Na";
    public static final String HA_SIGLUM = "Ha";
    public static final String SO_SIGLUM = "So";
    public static final String AG_SIGLUM = "Ag";
    public static final String ZA_SIGLUM = "Za";
    public static final String ML_SIGLUM = "Ml";
    public static final String MT_SIGLUM = "Mt";
    public static final String MK_SIGLUM = "Mk";
    public static final String LK_SIGLUM = "Łk";
    public static final String J_SIGLUM = "J";
    public static final String DZ_SIGLUM = "Dz";
    public static final String RZ_SIGLUM = "Rz";
    public static final String KOR_1_SIGLUM = "1Kor";
    public static final String KOR_2_SIGLUM = "2Kor";
    public static final String GA_SIGLUM = "Ga";
    public static final String EF_SIGLUM = "Ef";
    public static final String FLP_SIGLUM = "Flp";
    public static final String KOL_SIGLUM = "Kol";
    public static final String TES_1_SIGLUM = "1Tes";
    public static final String TES_2_SIGLUM = "2Tes";
    public static final String TM_1_SIGLUM = "1Tm";
    public static final String TM_2_SIGLUM = "2Tm";
    public static final String TT_SIGLUM = "Tt";
    public static final String FLM_SIGLUM = "Flm";
    public static final String HBR_SIGLUM = "Hbr";
    public static final String JK_SIGLUM = "Jk";
    public static final String P_1_SIGLUM = "1P";
    public static final String P_2_SIGLUM = "2P";
    public static final String J_1_SIGLUM = "1J";
    public static final String J_2_SIGLUM = "2J";
    public static final String J_3_SIGLUM = "3J";
    public static final String JUD_SIGLUM = "Jud";
    public static final String AP_SIGLUM = "Ap";
    public static final String RDZ_NAME = "Księga Rodzaju";
    public static final String WJ_NAME = "Księga Wyjścia";
    public static final String KPL_NAME = "Księga Kapłańska";
    public static final String LB_NAME = "Księga Liczb";
    public static final String PWT_NAME = "Księga Powtórzonego Prawa";
    public static final String JOZ_NAME = "Księga Jozuego";
    public static final String SDZ_NAME = "Księga Sędziów";
    public static final String RT_NAME = "Księga Rut";
    public static final String SM_1_NAME = "1. Księga Samuela";
    public static final String SM_2_NAME = "2. Księga Samuela";
    public static final String KRL_1_NAME = "1. Księga Królewska";
    public static final String KRL_2_NAME = "2. Księga Królewska";
    public static final String KRN_1_NAME = "1. Księga Kronik";
    public static final String KRN_2_NAME = "2. Księga Kronik";
    public static final String EZD_NAME = "Księga Ezdrasza";
    public static final String NE_NAME = "Księga Nehemiasza";
    public static final String TB_NAME = "Księga Tobiasza";
    public static final String JDT_NAME = "Księga Judyty";
    public static final String EST_NAME = "Księga Estery";
    public static final String MCH_1_NAME = "1. Księga Machabejska";
    public static final String MCH_2_NAME = "2. Księga Machabejska";
    public static final String HI_NAME = "Księga Hioba";
    public static final String PS_NAME = "Księga Psalmów";
    public static final String PRZ_NAME = "Księga Przysłów";
    public static final String KOH_NAME = "Księga Koheleta";
    public static final String PNP_NAME = "Pieśń nad Pieśniami";
    public static final String MDR_NAME = "Księga Mądrości";
    public static final String SYR_NAME = "Mądrość Syracha (Syracydesa)";
    public static final String IZ_NAME = "Księga Izajasza";
    public static final String JR_NAME = "Księga Jeremiasza";
    public static final String LM_NAME = "Lamentacje";
    public static final String BA_NAME = "Księga Barucha";
    public static final String EZ_NAME = "Księga Ezechiela";
    public static final String DN_NAME = "Księga Daniela";
    public static final String OZ_NAME = "Księga Ozeasza";
    public static final String JL_NAME = "Księga Joela";
    public static final String AM_NAME = "Księga Amosa";
    public static final String AB_NAME = "Księga Abdiama";
    public static final String JON_NAME = "Księga Jonasza";
    public static final String MI_NAME = "Księga Micheasza";
    public static final String NA_NAME = "Księga Nahuma";
    public static final String HA_NAME = "Księga Habakuka";
    public static final String SO_NAME = "Księga Sofoniasza";
    public static final String AG_NAME = "Księga Aggeusza";
    public static final String ZA_NAME = "Księga Zachariasza";
    public static final String ML_NAME = "Księga Malachiasza";
    public static final String MT_NAME = "Ewangelia wg św. Mateusza";
    public static final String MK_NAME = "Ewangelia wg św. Marka";
    public static final String LK_NAME = "Ewangelia wg św. Łukasza";
    public static final String J_NAME = "Ewangelia wg św. Jana";
    public static final String DZ_NAME = "Dzieje Apostolskie";
    public static final String RZ_NAME = "List do Rzymian";
    public static final String KOR_1_NAME = "1. List do Koryntian";
    public static final String KOR_2_NAME = "2. List do Koryntian";
    public static final String GA_NAME = "List do Galatów";
    public static final String EF_NAME = "List do Efezjan";
    public static final String FLP_NAME = "List do Filipian";
    public static final String KOL_NAME = "List do Kolosan";
    public static final String TES_1_NAME = "1. List do Tesaloniczan";
    public static final String TES_2_NAME = "2. List do Tesaloniczan";
    public static final String TM_1_NAME = "1. List do Tymoteusza";
    public static final String TM_2_NAME = "2. List do Tymoteusza";
    public static final String TT_NAME = "List do Tytusa";
    public static final String FLM_NAME = "List do Filemona";
    public static final String HBR_NAME = "List do Hebrajczyków";
    public static final String JK_NAME = "List św. Jakuba";
    public static final String P_1_NAME = "1. List św. Piotra";
    public static final String P_2_NAME = "2. List św. Piotra";
    public static final String J_1_NAME = "1. List św. Jana";
    public static final String J_2_NAME = "2. List św. Jana";
    public static final String J_3_NAME = "3. List św. Jana";
    public static final String JUD_NAME = "List św. Judy";
    public static final String AP_NAME = "Apokalipsa wg św. Jana";

    public static final List<TOME_ID> OLD_TESTAMENT_TOMES =
            List.of(RDZ, WJ, KPL, LB, PWT, JOZ, SDZ, RT, SM_1, SM_2, KRL_1, KRL_2, KRN_1, KRN_2, EZD,
                    NE, TB, JDT, EST, MCH_1, MCH_2, HI, PS, PRZ, KOH, PNP, MDR, SYR, IZ, JR,
                    LM, BA, EZ, DN, OZ, JL, AM, AB, JON, MI, NA, HA, SO, AG, ZA, ML);
    public static final List<TOME_ID> NEW_TESTAMENT_TOMES =
            List.of(MT, MK, LK, J, DZ, RZ, KOR_1, KOR_2, GA, EF, FLP, KOL, TES_1, TES_2,
                    TM_1, TM_2, TT, FLM, HBR, JK, P_1, P_2, J_1, J_2, J_3, JUD, AP);

    public static final BidiMap TOME_ORDER_MAP = new DualHashBidiMap() {{
        put(1, RDZ);
        put(2, WJ);
        put(3, KPL);
        put(4, LB);
        put(5, PWT);
        put(6, JOZ);
        put(7, SDZ);
        put(8, RT);
        put(9, SM_1);
        put(10, SM_2);
        put(11, KRL_1);
        put(12, KRL_2);
        put(13, KRN_1);
        put(14, KRN_2);
        put(15, EZD);
        put(16, NE);
        put(17, TB);
        put(18, JDT);
        put(19, EST);
        put(20, MCH_1);
        put(21, MCH_2);
        put(22, HI);
        put(23, PS);
        put(24, PRZ);
        put(25, KOH);
        put(26, PNP);
        put(27, MDR);
        put(28, SYR);
        put(29, IZ);
        put(30, JR);
        put(31, LM);
        put(32, BA);
        put(33, EZ);
        put(34, DN);
        put(35, OZ);
        put(36, JL);
        put(37, AM);
        put(38, AB);
        put(39, JON);
        put(40, MI);
        put(41, NA);
        put(42, HA);
        put(43, SO);
        put(44, AG);
        put(45, ZA);
        put(46, ML);
        put(47, MT);
        put(48, MK);
        put(49, LK);
        put(50, J);
        put(51, DZ);
        put(52, RZ);
        put(53, KOR_1);
        put(54, KOR_2);
        put(55, GA);
        put(56, EF);
        put(57, FLP);
        put(58, KOL);
        put(59, TES_1);
        put(60, TES_2);
        put(61, TM_1);
        put(62, TM_2);
        put(63, TT);
        put(64, FLM);
        put(65, HBR);
        put(66, JK);
        put(67, P_1);
        put(68, P_2);
        put(69, J_1);
        put(70, J_2);
        put(71, J_3);
        put(72, JUD);
        put(73, AP);
    }};
    public static final Map<TOME_ID, Integer> TOME_SIZE_MAP = new HashMap<>() {{
        put(RDZ, 50);
        put(WJ, 40);
        put(KPL, 27);
        put(LB, 36);
        put(PWT, 34);
        put(JOZ, 24);
        put(SDZ, 21);
        put(RT, 4);
        put(SM_1, 31);
        put(SM_2, 24);
        put(KRL_1, 22);
        put(KRL_2, 25);
        put(KRN_1, 29);
        put(KRN_2, 36);
        put(EZD, 10);
        put(NE, 13);
        put(TB, 14);
        put(JDT, 16);
        put(EST, 10);
        put(MCH_1, 16);
        put(MCH_2, 15);
        put(HI, 42);
        put(PS, 150);
        put(PRZ, 31);
        put(KOH, 12);
        put(PNP, 8);
        put(MDR, 19);
        put(SYR, 52);
        put(IZ, 66);
        put(JR, 52);
        put(LM, 5);
        put(BA, 6);
        put(EZ, 48);
        put(DN, 14);
        put(OZ, 14);
        put(JL, 4);
        put(AM, 9);
        put(AB, 1);
        put(JON, 4);
        put(MI, 7);
        put(NA, 3);
        put(HA, 3);
        put(SO, 3);
        put(AG, 2);
        put(ZA, 14);
        put(ML, 3);
        put(MT, 28);
        put(MK, 16);
        put(LK, 24);
        put(J, 21);
        put(DZ, 28);
        put(RZ, 16);
        put(KOR_1, 16);
        put(KOR_2, 13);
        put(GA, 6);
        put(EF, 6);
        put(FLP, 4);
        put(KOL, 4);
        put(TES_1, 5);
        put(TES_2, 3);
        put(TM_1, 6);
        put(TM_2, 4);
        put(TT, 3);
        put(FLM, 1);
        put(HBR, 13);
        put(JK, 5);
        put(P_1, 5);
        put(P_2, 3);
        put(J_1, 5);
        put(J_2, 1);
        put(J_3, 1);
        put(JUD, 1);
        put(AP, 22);
    }};
    public static final Map<TOME_ID, String> TOME_FIRST_CHAPTER_MAP = new HashMap<>() {{
        put(RDZ, "1");
        put(WJ, "1");
        put(KPL, "1");
        put(LB, "1");
        put(PWT, "1");
        put(JOZ, "1");
        put(SDZ, "1");
        put(RT, "1");
        put(SM_1, "1");
        put(SM_2, "1");
        put(KRL_1, "1");
        put(KRL_2, "1");
        put(KRN_1, "1");
        put(KRN_2, "1");
        put(EZD, "1");
        put(NE, "1");
        put(TB, "1");
        put(JDT, "1");
        put(EST, "1");
        put(MCH_1, "1");
        put(MCH_2, "1");
        put(HI, "1");
        put(PS, "1");
        put(PRZ, "1");
        put(KOH, "1");
        put(PNP, "1");
        put(MDR, "1");
        put(SYR, "Prolog");
        put(IZ, "1");
        put(JR, "1");
        put(LM, "1");
        put(BA, "1");
        put(EZ, "1");
        put(DN, "1");
        put(OZ, "1");
        put(JL, "1");
        put(AM, "1");
        put(AB, "1");
        put(JON, "1");
        put(MI, "1");
        put(NA, "1");
        put(HA, "1");
        put(SO, "1");
        put(AG, "1");
        put(ZA, "1");
        put(ML, "1");
        put(MT, "1");
        put(MK, "1");
        put(LK, "1");
        put(J, "1");
        put(DZ, "1");
        put(RZ, "1");
        put(KOR_1, "1");
        put(KOR_2, "1");
        put(GA, "1");
        put(EF, "1");
        put(FLP, "1");
        put(KOL, "1");
        put(TES_1, "1");
        put(TES_2, "1");
        put(TM_1, "1");
        put(TM_2, "1");
        put(TT, "1");
        put(FLM, "1");
        put(HBR, "1");
        put(JK, "1");
        put(P_1, "1");
        put(P_2, "1");
        put(J_1, "1");
        put(J_2, "1");
        put(J_3, "1");
        put(JUD, "1");
        put(AP, "1");
    }};
    public static final Map<TOME_ID, String> TOME_LAST_CHAPTER_MAP = new HashMap<>() {{
        put(RDZ, "50");
        put(WJ, "40");
        put(KPL, "27");
        put(LB, "36");
        put(PWT, "34");
        put(JOZ, "24");
        put(SDZ, "21");
        put(RT, "4");
        put(SM_1, "31");
        put(SM_2, "24");
        put(KRL_1, "22");
        put(KRL_2, "25");
        put(KRN_1, "29");
        put(KRN_2, "36");
        put(EZD, "10");
        put(NE, "13");
        put(TB, "14");
        put(JDT, "16");
        put(EST, "10");
        put(MCH_1, "16");
        put(MCH_2, "15");
        put(HI, "42");
        put(PS, "150");
        put(PRZ, "31");
        put(KOH, "12");
        put(PNP, "8");
        put(MDR, "19");
        put(SYR, "51");
        put(IZ, "66");
        put(JR, "52");
        put(LM, "5");
        put(BA, "6");
        put(EZ, "48");
        put(DN, "14");
        put(OZ, "14");
        put(JL, "4");
        put(AM, "9");
        put(AB, "1");
        put(JON, "4");
        put(MI, "7");
        put(NA, "3");
        put(HA, "3");
        put(SO, "3");
        put(AG, "2");
        put(ZA, "14");
        put(ML, "3");
        put(MT, "28");
        put(MK, "16");
        put(LK, "24");
        put(J, "21");
        put(DZ, "28");
        put(RZ, "16");
        put(KOR_1, "16");
        put(KOR_2, "13");
        put(GA, "6");
        put(EF, "6");
        put(FLP, "4");
        put(KOL, "4");
        put(TES_1, "5");
        put(TES_2, "3");
        put(TM_1, "6");
        put(TM_2, "4");
        put(TT, "3");
        put(FLM, "1");
        put(HBR, "13");
        put(JK, "5");
        put(P_1, "5");
        put(P_2, "3");
        put(J_1, "5");
        put(J_2, "1");
        put(J_3, "1");
        put(JUD, "1");
        put(AP, "22");
    }};
    public static final BidiMap TOME_SIGLA_MAP = new DualHashBidiMap() {{
        put(TOME_ID.RDZ, RDZ_SIGLUM);
        put(TOME_ID.WJ, WJ_SIGLUM);
        put(TOME_ID.KPL, KPL_SIGLUM);
        put(TOME_ID.LB, LB_SIGLUM);
        put(TOME_ID.PWT, PWT_SIGLUM);
        put(TOME_ID.JOZ, JOZ_SIGLUM);
        put(TOME_ID.SDZ, SDZ_SIGLUM);
        put(TOME_ID.RT, RT_SIGLUM);
        put(TOME_ID.SM_1, SM_1_SIGLUM);
        put(TOME_ID.SM_2, SM_2_SIGLUM);
        put(TOME_ID.KRL_1, KRL_1_SIGLUM);
        put(TOME_ID.KRL_2, KRL_2_SIGLUM);
        put(TOME_ID.KRN_1, KRN_1_SIGLUM);
        put(TOME_ID.KRN_2, KRN_2_SIGLUM);
        put(TOME_ID.EZD, EZD_SIGLUM);
        put(TOME_ID.NE, NE_SIGLUM);
        put(TOME_ID.TB, TB_SIGLUM);
        put(TOME_ID.JDT, JDT_SIGLUM);
        put(TOME_ID.EST, EST_SIGLUM);
        put(TOME_ID.MCH_1, MCH_1_SIGLUM);
        put(TOME_ID.MCH_2, MCH_2_SIGLUM);
        put(TOME_ID.HI, HI_SIGLUM);
        put(TOME_ID.PS, PS_SIGLUM);
        put(TOME_ID.PRZ, PRZ_SIGLUM);
        put(TOME_ID.KOH, KOH_SIGLUM);
        put(TOME_ID.PNP, PNP_SIGLUM);
        put(TOME_ID.MDR, MDR_SIGLUM);
        put(TOME_ID.SYR, SYR_SIGLUM);
        put(TOME_ID.IZ, IZ_SIGLUM);
        put(TOME_ID.JR, JR_SIGLUM);
        put(TOME_ID.LM, LM_SIGLUM);
        put(TOME_ID.BA, BA_SIGLUM);
        put(TOME_ID.EZ, EZ_SIGLUM);
        put(TOME_ID.DN, DN_SIGLUM);
        put(TOME_ID.OZ, OZ_SIGLUM);
        put(TOME_ID.JL, JL_SIGLUM);
        put(TOME_ID.AM, AM_SIGLUM);
        put(TOME_ID.AB, AB_SIGLUM);
        put(TOME_ID.JON, JON_SIGLUM);
        put(TOME_ID.MI, MI_SIGLUM);
        put(TOME_ID.NA, NA_SIGLUM);
        put(TOME_ID.HA, HA_SIGLUM);
        put(TOME_ID.SO, SO_SIGLUM);
        put(TOME_ID.AG, AG_SIGLUM);
        put(TOME_ID.ZA, ZA_SIGLUM);
        put(TOME_ID.ML, ML_SIGLUM);
        put(TOME_ID.MT, MT_SIGLUM);
        put(TOME_ID.MK, MK_SIGLUM);
        put(TOME_ID.LK, LK_SIGLUM);
        put(TOME_ID.J, J_SIGLUM);
        put(TOME_ID.DZ, DZ_SIGLUM);
        put(TOME_ID.RZ, RZ_SIGLUM);
        put(TOME_ID.KOR_1, KOR_1_SIGLUM);
        put(TOME_ID.KOR_2, KOR_2_SIGLUM);
        put(TOME_ID.GA, GA_SIGLUM);
        put(TOME_ID.EF, EF_SIGLUM);
        put(TOME_ID.FLP, FLP_SIGLUM);
        put(TOME_ID.KOL, KOL_SIGLUM);
        put(TOME_ID.TES_1, TES_1_SIGLUM);
        put(TOME_ID.TES_2, TES_2_SIGLUM);
        put(TOME_ID.TM_1, TM_1_SIGLUM);
        put(TOME_ID.TM_2, TM_2_SIGLUM);
        put(TOME_ID.TT, TT_SIGLUM);
        put(TOME_ID.FLM, FLM_SIGLUM);
        put(TOME_ID.HBR, HBR_SIGLUM);
        put(TOME_ID.JK, JK_SIGLUM);
        put(TOME_ID.P_1, P_1_SIGLUM);
        put(TOME_ID.P_2, P_2_SIGLUM);
        put(TOME_ID.J_1, J_1_SIGLUM);
        put(TOME_ID.J_2, J_2_SIGLUM);
        put(TOME_ID.J_3, J_3_SIGLUM);
        put(TOME_ID.JUD, JUD_SIGLUM);
        put(TOME_ID.JUD, JUD_SIGLUM);
        put(TOME_ID.AP, AP_SIGLUM);
    }};
    public static final Map<TOME_ID, String> TOME_NAMES_MAP = new HashMap<>() {{
        put(TOME_ID.RDZ, WJ_NAME);
        put(TOME_ID.WJ, KPL_NAME);
        put(TOME_ID.KPL, LB_NAME);
        put(TOME_ID.LB, PWT_NAME);
        put(TOME_ID.PWT, JOZ_NAME);
        put(TOME_ID.JOZ, SDZ_NAME);
        put(TOME_ID.SDZ, RT_NAME);
        put(TOME_ID.RT, SM_1_NAME);
        put(TOME_ID.SM_1, SM_2_NAME);
        put(TOME_ID.SM_2, KRL_1_NAME);
        put(TOME_ID.KRL_1, KRL_2_NAME);
        put(TOME_ID.KRL_2, KRN_1_NAME);
        put(TOME_ID.KRN_1, KRN_2_NAME);
        put(TOME_ID.KRN_2, EZD_NAME);
        put(TOME_ID.EZD, NE_NAME);
        put(TOME_ID.NE, TB_NAME);
        put(TOME_ID.TB, JDT_NAME);
        put(TOME_ID.JDT, EST_NAME);
        put(TOME_ID.EST, MCH_1_NAME);
        put(TOME_ID.MCH_1, MCH_2_NAME);
        put(TOME_ID.MCH_2, HI_NAME);
        put(TOME_ID.HI, PS_NAME);
        put(TOME_ID.PS, PRZ_NAME);
        put(TOME_ID.PRZ, KOH_NAME);
        put(TOME_ID.KOH, PNP_NAME);
        put(TOME_ID.PNP, MDR_NAME);
        put(TOME_ID.MDR, SYR_NAME);
        put(TOME_ID.SYR, IZ_NAME);
        put(TOME_ID.IZ, JR_NAME);
        put(TOME_ID.JR, LM_NAME);
        put(TOME_ID.LM, BA_NAME);
        put(TOME_ID.BA, EZ_NAME);
        put(TOME_ID.EZ, DN_NAME);
        put(TOME_ID.DN, OZ_NAME);
        put(TOME_ID.OZ, JL_NAME);
        put(TOME_ID.JL, AM_NAME);
        put(TOME_ID.AM, AB_NAME);
        put(TOME_ID.AB, JON_NAME);
        put(TOME_ID.JON, MI_NAME);
        put(TOME_ID.MI, NA_NAME);
        put(TOME_ID.NA, HA_NAME);
        put(TOME_ID.HA, SO_NAME);
        put(TOME_ID.SO, AG_NAME);
        put(TOME_ID.AG, ZA_NAME);
        put(TOME_ID.ZA, ML_NAME);
        put(TOME_ID.MT, MT_NAME);
        put(TOME_ID.MK, MK_NAME);
        put(TOME_ID.LK, LK_NAME);
        put(TOME_ID.J, J_NAME);
        put(TOME_ID.DZ, DZ_NAME);
        put(TOME_ID.RZ, RZ_NAME);
        put(TOME_ID.KOR_1, KOR_1_NAME);
        put(TOME_ID.KOR_2, KOR_2_NAME);
        put(TOME_ID.GA, GA_NAME);
        put(TOME_ID.EF, EF_NAME);
        put(TOME_ID.FLP, FLP_NAME);
        put(TOME_ID.KOL, KOL_NAME);
        put(TOME_ID.TES_1, TES_1_NAME);
        put(TOME_ID.TES_2, TES_2_NAME);
        put(TOME_ID.TM_1, TM_1_NAME);
        put(TOME_ID.TM_2, TM_2_NAME);
        put(TOME_ID.TT, TT_NAME);
        put(TOME_ID.FLM, FLM_NAME);
        put(TOME_ID.HBR, HBR_NAME);
        put(TOME_ID.JK, JK_NAME);
        put(TOME_ID.P_1, P_1_NAME);
        put(TOME_ID.P_2, P_2_NAME);
        put(TOME_ID.J_1, J_1_NAME);
        put(TOME_ID.J_2, J_2_NAME);
        put(TOME_ID.J_3, J_3_NAME);
        put(TOME_ID.JUD, JUD_NAME);
        put(TOME_ID.AP, AP_NAME);
    }};
    public static final Map<SUPPLEMENT_TYPE, String> SUPPLEMENT_NAMES_MAP = new HashMap<>() {{
        put(SUPPLEMENT_TYPE.DEF, "Definition");
        put(SUPPLEMENT_TYPE.DICT, "Dictionary Entry");
    }};
}
